In [2]:
import tbapy
import pandas as pd
from itertools import permutations, combinations, chain
import os 
import collections
import base64
import statbotics

In [3]:
tbakey = os.environ.get('tbakey')
tba = tbapy.TBA(tbakey)
sb = statbotics.Statbotics()

In [4]:
event = '2025hop'

In [5]:
# import statbotics

# sb = statbotics.Statbotics()
# sb.get_team(254)

In [6]:
teams = []

for i in tba.event_teams(event):
    teams += [int(i['key'][-len(i['key'])+3:])]
    
teams

[10157,
 10224,
 1038,
 10479,
 1153,
 1241,
 1506,
 1700,
 1768,
 1902,
 195,
 2075,
 2080,
 2200,
 230,
 2383,
 2470,
 2485,
 2491,
 2522,
 2539,
 2706,
 2767,
 2783,
 2877,
 2960,
 3045,
 3130,
 3197,
 33,
 3339,
 3473,
 3656,
 3794,
 3814,
 3882,
 3928,
 3970,
 4009,
 4145,
 467,
 4728,
 4907,
 5013,
 51,
 5181,
 5193,
 540,
 5736,
 5817,
 5985,
 5987,
 6324,
 6621,
 6647,
 6652,
 6873,
 70,
 7421,
 7632,
 781,
 7902,
 801,
 8177,
 8570,
 8595,
 86,
 888,
 9134,
 9245,
 9450,
 9496,
 9545,
 9635,
 973]

In [70]:
df2 = pd.DataFrame(columns=['teamNumber','match', 'climb'])
for t in teams:
    print(t)
    max_week = 0
    for e in tba.team_events(t, 2025):
        if e['week'] is not None:
            max_week = max(max_week, e['week'])
    for e in tba.team_events(t, 2025):
        if e['week'] == max_week:
            for m in tba.team_matches(t, e['key']):
                blue_teams = m['alliances']['blue']['team_keys']
                red_teams = m['alliances']['red']['team_keys']
                
                team_string = 'frc' + str(t)
                
                if team_string in blue_teams:
                    if team_string == blue_teams[0]:
                        end_status = m['score_breakdown']['blue']['endGameRobot1']
                    elif team_string == blue_teams[1]:
                        end_status = m['score_breakdown']['blue']['endGameRobot2']
                    elif team_string == blue_teams[2]:
                        end_status = m['score_breakdown']['blue']['endGameRobot3']
                elif team_string in red_teams:
                    if team_string == red_teams[0]:
                        end_status = m['score_breakdown']['red']['endGameRobot1']
                    elif team_string == red_teams[1]:
                        end_status = m['score_breakdown']['red']['endGameRobot2']
                    elif team_string == red_teams[2]:
                        end_status = m['score_breakdown']['red']['endGameRobot3']
                
                new_row = [t, m['key'], end_status]
                df2.loc[len(df2)] = new_row

10157
10224
1038
10479
1153
1241
1506
1700
1768
1902
195
2075
2080
2200
230
2383
2470
2485
2491
2522
2539
2706
2767
2783
2877
2960
3045
3130
3197
33
3339
3473
3656
3794
3814
3882
3928
3970
4009
4145
467
4728
4907
5013
51
5181
5193
540
5736
5817
5985
5987
6324
6621
6647
6652
6873
70
7421
7632
781
7902
801
8177
8570
8595
86
888
9134
9245
9450
9496
9545
9635
973

,total_points,auto_points,teleop_points,endgame_points,auto_rp,coral_rp,barge_rp,tiebreaker_points,auto_leave_points,auto_coral,...,processor_algae_points,net_algae,net_algae_points,total_algae_points,total_game_pieces,barge_points,rp_1,rp_2,rp_3,teamNumber
10157,22.24,5.84,11.82,4.58,0.2082,-0.0031,0.16795,0.25,2.58,0.67,...,1.51,-0.04,-0.16,1.35,3.62,4.58,0.2082,-0.0031,0.16795,10157

In [95]:
dict_ = sb.get_team_year(teams[0], 2025)['epa']['breakdown']
dict_['teamNumber'] = teams[0]
df3 = pd.DataFrame(dict_, index=[dict_['teamNumber']])

for t in teams[1:]:
    print(t)
    new_dict = sb.get_team_year(t, 2025)['epa']['breakdown']
    new_dict['teamNumber'] = t
    df3 = pd.concat([df3, pd.DataFrame(new_dict, index=[new_dict['teamNumber']])])

10224
1038
10479
1153
1241
1506
1700
1768
1902
195
2075
2080
2200
230
2383
2470
2485
2491
2522
2539
2706
2767
2783
2877
2960
3045
3130
3197
33
3339
3473
3656
3794
3814
3882
3928
3970
4009
4145
467
4728
4907
5013
51
5181
5193
540
5736
5817
5985
5987
6324
6621
6647
6652
6873
70
7421
7632
781
7902
801
8177
8570
8595
86
888
9134
9245
9450
9496
9545
9635
973

In [96]:
df3

,total_points,auto_points,teleop_points,endgame_points,auto_rp,coral_rp,barge_rp,tiebreaker_points,auto_leave_points,auto_coral,...,processor_algae_points,net_algae,net_algae_points,total_algae_points,total_game_pieces,barge_points,rp_1,rp_2,rp_3,teamNumber
10157,22.24,5.84,11.82,4.58,0.2082,-0.0031,0.16795,0.25,2.58,0.67,...,1.51,-0.04,-0.16,1.35,3.62,4.58,0.2082,-0.0031,0.16795,10157
10224,41.21,9.29,26.76,5.17,0.3639,0.2913,0.12808,0.25,2.96,0.96,...,2.37,0.12,0.50,2.87,7.62,5.17,0.3639,0.2913,0.12808,10224
1038,17.93,3.66,13.85,0.42,0.1874,0.1245,-0.04286,0.11,3.30,0.09,...,2.79,0.88,3.53,6.32,3.90,0.42,0.1874,0.1245,-0.04286,1038
10479,56.97,11.66,37.78,7.53,0.2073,0.3192,0.23816,0.20,2.79,1.42,...,1.13,0.27,1.07,2.20,10.60,7.53,0.2073,0.3192,0.23816,10479
1153,77.48,13.08,53.94,10.47,0.5288,0.5257,0.63935,0.32,3.22,1.91,...,1.30,4.01,16.04,17.34,15.85,10.47,0.5288,0.5257,0.63935,1153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9450,81.44,18.87,52.37,10.19,0.5359,0.3694,0.63624,0.07,3.00,2.39,...,0.81,2.66,10.64,11.45,17.08,10.19,0.5359,0.3694,0.63624,9450
9496,79.02,21.67,50.70,6.65,0.6197,0.6528,0.43094,0.21,3.17,2.61,...,2.88,2.26,9.05,11.93,16.59,6.65,0.6197,0.6528,0.43094,9496
9545,11.23,2.69,6.06,2.48,-0.1736,-0.1739,0.06846,-0.01,1.10,0.28,...,0.05,0.23,0.90,0.95,1.14,2.48,-0.1736,-0.1739,0.06846,9545
9635,40.32,11.80,27.30,1.22,0.4199,-0.0013,0.01054,0.03,2.90,1.31,...,0.57,1.06,4.24,4.81,7.51,1.22,0.4199,-0.0013,0.01054,9635
973,60.12,17.11,34.88,8.13,0.6094,0.3352,0.39269,0.08,3.32,1.99,...,0.22,0.82,3.26,3.48,10.69,8.13,0.6094,0.3352,0.39269,973

In [97]:
df3.to_csv('hopper_epas.csv')

In [71]:
df2.to_csv('hopper_climbs.csv')

In [48]:
tba.team_matches(1902, tba.team_events(1902, 2025)[1]['key'])

[Match({'actual_time': 1742159719, 'alliances': {'blue': {'dq_team_keys': [], 'score': 114, 'surrogate_team_keys': [], 'team_keys': ['frc108', 'frc8788', 'frc233']}, 'red': {'dq_team_keys': [], 'score': 163, 'surrogate_team_keys': [], 'team_keys': ['frc1902', 'frc386', 'frc6184']}}, 'comp_level': 'f', 'event_key': '2025flta', 'key': '2025flta_f1m1', 'match_number': 1, 'post_result_time': 1742159943, 'predicted_time': 1742155718, 'score_breakdown': {'blue': {'adjustPoints': 0, 'algaePoints': 4, 'autoBonusAchieved': False, 'autoCoralCount': 3, 'autoCoralPoints': 21, 'autoLineRobot1': 'Yes', 'autoLineRobot2': 'Yes', 'autoLineRobot3': 'Yes', 'autoMobilityPoints': 9, 'autoPoints': 30, 'autoReef': {'botRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'midRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'tba_botRowCount': 0, 'tba_midRowCount': 0, 'tba_topRowCount': 3, 'topRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': True, 'nodeJ': False, 'nodeK': True, 'nodeL': True}, 'trough': 0}, 'bargeBonusAchieved': False, 'coopertitionCriteriaMet': False, 'coralBonusAchieved': False, 'endGameBargePoints': 0, 'endGameRobot1': 'None', 'endGameRobot2': 'None', 'endGameRobot3': 'None', 'foulCount': 1, 'foulPoints': 0, 'g206Penalty': False, 'g410Penalty': False, 'g418Penalty': False, 'g428Penalty': False, 'netAlgaeCount': 1, 'rp': 0, 'techFoulCount': 2, 'teleopCoralCount': 18, 'teleopCoralPoints': 80, 'teleopPoints': 84, 'teleopReef': {'botRow': {'nodeA': False, 'nodeB': False, 'nodeC': True, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'midRow': {'nodeA': True, 'nodeB': True, 'nodeC': True, 'nodeD': True, 'nodeE': True, 'nodeF': True, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': True, 'nodeL': True}, 'tba_botRowCount': 1, 'tba_midRowCount': 8, 'tba_topRowCount': 12, 'topRow': {'nodeA': True, 'nodeB': True, 'nodeC': True, 'nodeD': True, 'nodeE': True, 'nodeF': True, 'nodeG': True, 'nodeH': True, 'nodeI': True, 'nodeJ': True, 'nodeK': True, 'nodeL': True}, 'trough': 0}, 'totalPoints': 114, 'wallAlgaeCount': 0}, 'red': {'adjustPoints': 0, 'algaePoints': 0, 'autoBonusAchieved': False, 'autoCoralCount': 2, 'autoCoralPoints': 13, 'autoLineRobot1': 'Yes', 'autoLineRobot2': 'Yes', 'autoLineRobot3': 'Yes', 'autoMobilityPoints': 9, 'autoPoints': 22, 'autoReef': {'botRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'midRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': True, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'tba_botRowCount': 0, 'tba_midRowCount': 1, 'tba_topRowCount': 1, 'topRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': True, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'trough': 0}, 'bargeBonusAchieved': False, 'coopertitionCriteriaMet': False, 'coralBonusAchieved': False, 'endGameBargePoints': 16, 'endGameRobot1': 'Parked', 'endGameRobot2': 'DeepCage', 'endGameRobot3': 'Parked', 'foulCount': 0, 'foulPoints': 14, 'g206Penalty': False, 'g410Penalty': False, 'g418Penalty': False, 'g428Penalty': False, 'netAlgaeCount': 0, 'rp': 0, 'techFoulCount': 0, 'teleopCoralCount': 26, 'teleopCoralPoints': 111, 'teleopPoints': 127, 'teleopReef': {'botRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': True, 'nodeJ': True, 'nodeK': True, 'nodeL': True}, 'midRow': {'nodeA': True, 'nodeB': True, 'nodeC': True, 'nodeD': True, 'nodeE': True, 'nodeF': True, 'nodeG': True, 'nodeH': True, 'nodeI': True, 'nodeJ': True, 'nodeK': True, 'nodeL': True}, 'tba_botRowCount': 4, 'tba_midRowCount': 12, 'tba_topRowCount': 12, 'topRow': {'nodeA': True, 'nodeB': True, 'nodeC': True, 'nodeD': True, 'nodeE': True, 'nodeF': True, 'nodeG': True, 'nodeH': True, 'nodeI': True, 'nodeJ': True, 'nodeK': True, 'nodeL': True}, 'trough': 0}, 'totalPoints': 163, 'wallAlgaeCount': 0}}, 'set_number': 1, 'time': 1742154240, 'videos': [{'key': 'XYQCvVjUzvw', 'type': 'youtube'}, {'key': 'BimF8wRKOu4', 'type': 'youtube'}], 'winning_alliance': 'red'}),
 Match({'actual_time': 1742161092, 'alliances': {'blue': {'dq_team_keys': [], 'score': 153, 'surrogate_team_keys': [], 'team_keys': ['frc108', 'frc8788', 'frc233']}, 'red': {'dq_team_keys': [], 'score': 173, 'surrogate_team_keys': [], 'team_keys': ['frc1902', 'frc386', 'frc6184']}}, 'comp_level': 'f', 'event_key': '2025flta', 'key': '2025flta_f1m2', 'match_number': 2, 'post_result_time': 1742161321, 'predicted_time': 1742157182, 'score_breakdown': {'blue': {'adjustPoints': 0, 'algaePoints': 40, 'autoBonusAchieved': False, 'autoCoralCount': 4, 'autoCoralPoints': 24, 'autoLineRobot1': 'Yes', 'autoLineRobot2': 'Yes', 'autoLineRobot3': 'Yes', 'autoMobilityPoints': 9, 'autoPoints': 33, 'autoReef': {'botRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'midRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'tba_botRowCount': 0, 'tba_midRowCount': 0, 'tba_topRowCount': 3, 'topRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': True, 'nodeH': False, 'nodeI': True, 'nodeJ': False, 'nodeK': True, 'nodeL': False}, 'trough': 1}, 'bargeBonusAchieved': False, 'coopertitionCriteriaMet': False, 'coralBonusAchieved': False, 'endGameBargePoints': 4, 'endGameRobot1': 'Parked', 'endGameRobot2': 'None', 'endGameRobot3': 'Parked', 'foulCount': 2, 'foulPoints': 0, 'g206Penalty': False, 'g410Penalty': False, 'g418Penalty': False, 'g428Penalty': False, 'netAlgaeCount': 1, 'rp': 0, 'techFoulCount': 0, 'teleopCoralCount': 18, 'teleopCoralPoints': 76, 'teleopPoints': 120, 'teleopReef': {'botRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'midRow': {'nodeA': False, 'nodeB': True, 'nodeC': True, 'nodeD': True, 'nodeE': True, 'nodeF': True, 'nodeG': False, 'nodeH': False, 'nodeI': True, 'nodeJ': False, 'nodeK': True, 'nodeL': True}, 'tba_botRowCount': 0, 'tba_midRowCount': 8, 'tba_topRowCount': 11, 'topRow': {'nodeA': False, 'nodeB': True, 'nodeC': True, 'nodeD': True, 'nodeE': True, 'nodeF': True, 'nodeG': True, 'nodeH': True, 'nodeI': True, 'nodeJ': True, 'nodeK': True, 'nodeL': True}, 'trough': 2}, 'totalPoints': 153, 'wallAlgaeCount': 6}, 'red': {'adjustPoints': 0, 'algaePoints': 24, 'autoBonusAchieved': False, 'autoCoralCount': 4, 'autoCoralPoints': 26, 'autoLineRobot1': 'Yes', 'autoLineRobot2': 'Yes', 'autoLineRobot3': 'Yes', 'autoMobilityPoints': 9, 'autoPoints': 35, 'autoReef': {'botRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'midRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': True, 'nodeF': True, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'tba_botRowCount': 0, 'tba_midRowCount': 2, 'tba_topRowCount': 2, 'topRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': True, 'nodeJ': False, 'nodeK': False, 'nodeL': True}, 'trough': 0}, 'bargeBonusAchieved': False, 'coopertitionCriteriaMet': False, 'coralBonusAchieved': False, 'endGameBargePoints': 14, 'endGameRobot1': 'None', 'endGameRobot2': 'DeepCage', 'endGameRobot3': 'Parked', 'foulCount': 0, 'foulPoints': 4, 'g206Penalty': False, 'g410Penalty': False, 'g418Penalty': False, 'g428Penalty': False, 'netAlgaeCount': 6, 'rp': 0, 'techFoulCount': 0, 'teleopCoralCount': 22, 'teleopCoralPoints': 96, 'teleopPoints': 134, 'teleopReef': {'botRow': {'nodeA': True, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': True}, 'midRow': {'nodeA': True, 'nodeB': True, 'nodeC': True, 'nodeD': True, 'nodeE': True, 'nodeF': True, 'nodeG': True, 'nodeH': True, 'nodeI': True, 'nodeJ': True, 'nodeK': True, 'nodeL': True}, 'tba_botRowCount': 2, 'tba_midRowCount': 12, 'tba_topRowCount': 12, 'topRow': {'nodeA': True, 'nodeB': True, 'nodeC': True, 'nodeD': True, 'nodeE': True, 'nodeF': True, 'nodeG': True, 'nodeH': True, 'nodeI': True, 'nodeJ': True, 'nodeK': True, 'nodeL': True}, 'trough': 0}, 'totalPoints': 173, 'wallAlgaeCount': 0}}, 'set_number': 1, 'time': 1742155500, 'videos': [{'key': 'YcBE3916KFY', 'type': 'youtube'}], 'winning_alliance': 'red'}),
 Match({'actual_time': 1742051994, 'alliances': {'blue': {'dq_team_keys': [], 'score': 91, 'surrogate_team_keys': [], 'team_keys': ['frc79', 'frc9300', 'frc1902']}, 'red': {'dq_team_keys': [], 'score': 23, 'surrogate_team_keys': [], 'team_keys': ['frc10177', 'frc9493', 'frc1369']}}, 'comp_level': 'qm', 'event_key': '2025flta', 'key': '2025flta_qm15', 'match_number': 15, 'post_result_time': 1742052258, 'predicted_time': 1742052124, 'score_breakdown': {'blue': {'adjustPoints': 0, 'algaePoints': 16, 'autoBonusAchieved': True, 'autoCoralCount': 1, 'autoCoralPoints': 6, 'autoLineRobot1': 'Yes', 'autoLineRobot2': 'Yes', 'autoLineRobot3': 'Yes', 'autoMobilityPoints': 9, 'autoPoints': 15, 'autoReef': {'botRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'midRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': True, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'tba_botRowCount': 0, 'tba_midRowCount': 1, 'tba_topRowCount': 0, 'topRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'trough': 0}, 'bargeBonusAchieved': False, 'coopertitionCriteriaMet': True, 'coralBonusAchieved': False, 'endGameBargePoints': 6, 'endGameRobot1': 'Parked', 'endGameRobot2': 'Parked', 'endGameRobot3': 'Parked', 'foulCount': 1, 'foulPoints': 12, 'g206Penalty': False, 'g410Penalty': False, 'g418Penalty': False, 'g428Penalty': False, 'netAlgaeCount': 1, 'rp': 4, 'techFoulCount': 0, 'teleopCoralCount': 12, 'teleopCoralPoints': 42, 'teleopPoints': 64, 'teleopReef': {'botRow': {'nodeA': True, 'nodeB': False, 'nodeC': True, 'nodeD': False, 'nodeE': True, 'nodeF': True, 'nodeG': True, 'nodeH': True, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'midRow': {'nodeA': True, 'nodeB': True, 'nodeC': False, 'nodeD': False, 'nodeE': True, 'nodeF': True, 'nodeG': True, 'nodeH': True, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': True}, 'tba_botRowCount': 6, 'tba_midRowCount': 7, 'tba_topRowCount': 0, 'topRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'trough': 0}, 'totalPoints': 91, 'wallAlgaeCount': 2}, 'red': {'adjustPoints': 0, 'algaePoints': 8, 'autoBonusAchieved': False, 'autoCoralCount': 0, 'autoCoralPoints': 0, 'autoLineRobot1': 'Yes', 'autoLineRobot2': 'No', 'autoLineRobot3': 'Yes', 'autoMobilityPoints': 6, 'autoPoints': 6, 'autoReef': {'botRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'midRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'tba_botRowCount': 0, 'tba_midRowCount': 0, 'tba_topRowCount': 0, 'topRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'trough': 0}, 'bargeBonusAchieved': False, 'coopertitionCriteriaMet': False, 'coralBonusAchieved': False, 'endGameBargePoints': 4, 'endGameRobot1': 'None', 'endGameRobot2': 'Parked', 'endGameRobot3': 'Parked', 'foulCount': 3, 'foulPoints': 2, 'g206Penalty': False, 'g410Penalty': False, 'g418Penalty': False, 'g428Penalty': False, 'netAlgaeCount': 2, 'rp': 0, 'techFoulCount': 1, 'teleopCoralCount': 1, 'teleopCoralPoints': 3, 'teleopPoints': 15, 'teleopReef': {'botRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': True, 'nodeK': False, 'nodeL': False}, 'midRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'tba_botRowCount': 1, 'tba_midRowCount': 0, 'tba_topRowCount': 0, 'topRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'trough': 0}, 'totalPoints': 23, 'wallAlgaeCount': 0}}, 'set_number': 1, 'time': 1742049720, 'videos': [{'key': 'WnbKj8a2DF0', 'type': 'youtube'}], 'winning_alliance': 'blue'}),
 Match({'actual_time': 1742061108, 'alliances': {'blue': {'dq_team_keys': [], 'score': 108, 'surrogate_team_keys': [], 'team_keys': ['frc1902', 'frc9642', 'frc6473']}, 'red': {'dq_team_keys': [], 'score': 13, 'surrogate_team_keys': [], 'team_keys': ['frc9720', 'frc9313', 'frc4576']}}, 'comp_level': 'qm', 'event_key': '2025flta', 'key': '2025flta_qm28', 'match_number': 28, 'post_result_time': 1742061298, 'predicted_time': 1742061124, 'score_breakdown': {'blue': {'adjustPoints': 0, 'algaePoints': 12, 'autoBonusAchieved': False, 'autoCoralCount': 0, 'autoCoralPoints': 0, 'autoLineRobot1': 'Yes', 'autoLineRobot2': 'Yes', 'autoLineRobot3': 'No', 'autoMobilityPoints': 6, 'autoPoints': 6, 'autoReef': {'botRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'midRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'tba_botRowCount': 0, 'tba_midRowCount': 0, 'tba_topRowCount': 0, 'topRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'trough': 0}, 'bargeBonusAchieved': True, 'coopertitionCriteriaMet': True, 'coralBonusAchieved': False, 'endGameBargePoints': 16, 'endGameRobot1': 'DeepCage', 'endGameRobot2': 'Parked', 'endGameRobot3': 'Parked', 'foulCount': 0, 'foulPoints': 0, 'g206Penalty': False, 'g410Penalty': False, 'g418Penalty': False, 'g428Penalty': False, 'netAlgaeCount': 0, 'rp': 4, 'techFoulCount': 0, 'teleopCoralCount': 19, 'teleopCoralPoints': 74, 'teleopPoints': 102, 'teleopReef': {'botRow': {'nodeA': False, 'nodeB': True, 'nodeC': True, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': True, 'nodeJ': True, 'nodeK': True, 'nodeL': False}, 'midRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': True, 'nodeI': True, 'nodeJ': True, 'nodeK': True, 'nodeL': True}, 'tba_botRowCount': 5, 'tba_midRowCount': 5, 'tba_topRowCount': 7, 'topRow': {'nodeA': True, 'nodeB': True, 'nodeC': True, 'nodeD': True, 'nodeE': False, 'nodeF': True, 'nodeG': False, 'nodeH': True, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': True}, 'trough': 2}, 'totalPoints': 108, 'wallAlgaeCount': 2}, 'red': {'adjustPoints': 0, 'algaePoints': 0, 'autoBonusAchieved': False, 'autoCoralCount': 0, 'autoCoralPoints': 0, 'autoLineRobot1': 'No', 'autoLineRobot2': 'No', 'autoLineRobot3': 'Yes', 'autoMobilityPoints': 3, 'autoPoints': 3, 'autoReef': {'botRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'midRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'tba_botRowCount': 0, 'tba_midRowCount': 0, 'tba_topRowCount': 0, 'topRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'trough': 0}, 'bargeBonusAchieved': False, 'coopertitionCriteriaMet': False, 'coralBonusAchieved': False, 'endGameBargePoints': 6, 'endGameRobot1': 'Parked', 'endGameRobot2': 'Parked', 'endGameRobot3': 'Parked', 'foulCount': 0, 'foulPoints': 0, 'g206Penalty': False, 'g410Penalty': False, 'g418Penalty': False, 'g428Penalty': False, 'netAlgaeCount': 0, 'rp': 0, 'techFoulCount': 0, 'teleopCoralCount': 2, 'teleopCoralPoints': 4, 'teleopPoints': 10, 'teleopReef': {'botRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'midRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'tba_botRowCount': 0, 'tba_midRowCount': 0, 'tba_topRowCount': 0, 'topRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'trough': 2}, 'totalPoints': 13, 'wallAlgaeCount': 0}}, 'set_number': 1, 'time': 1742059320, 'videos': [{'key': '6Q4pZhIioPY', 'type': 'youtube'}], 'winning_alliance': 'blue'}),

In [5]:
teams = []

for i in tba.event_rankings(event)['rankings']:
    teams += [int(i['team_key'][-len(i['team_key'])+3:])]
    
teams

[]

In [6]:
dict1 = {}
for r in tba.event_rankings(event)['rankings']:
    team_key = r['team_key']
    dict1[team_key] = r['rank']
    
dict2 = {}
for key, value in tba.event_district_points(event)['points'].items():
    if (value['alliance_points'] == 0) and key != 'frcNone':
        dict2[key] = dict1[key]

print('Top 5 Ranked Teams Left out of Elims')
print(sorted(dict2.items(), key=lambda x:x[1]))

Top 5 Ranked Teams Left out of Elims
[('frc8349', 15), ('frc2708', 16), ('frc1305', 17), ('frc2198', 23), ('frc6632', 24), ('frc5031', 25), ('frc9659', 27), ('frc10167', 29), ('frc7659', 32), ('frc2634', 33), ('frc7058', 34), ('frc2706', 36), ('frc8731', 37), ('frc10015', 38), ('frc5912', 39), ('frc9262', 40), ('frc9263', 41), ('frc7475', 42), ('frc6135', 43), ('frc7136', 44), ('frc2852', 45), ('frc10027', 46), ('frc10218', 47), ('frc5719', 48), ('frc771', 49), ('frc7757', 50)]

In [7]:
list1 = []
for a in tba.event_alliances(event):
    team = a['picks'][0]
    opr = tba.event_oprs(event)['oprs'][team]
    dict1 = {team:opr}
    list1.append(dict1)

counter = collections.Counter()
for d in list1:
    counter.update(d)
    
res = dict(sorted(counter.items(), key=lambda item: item[1], reverse=False))

print('Team Captain with the lowest OPR')
res

Team Captain with the lowest OPR

{'frc9525': 37.94512908583002,
 'frc4940': 58.88334724038052,
 'frc865': 65.20524207407362,
 'frc1325': 65.52724152599652,
 'frc9785': 69.35526313087217,
 'frc4039': 70.62654161533224,
 'frc1241': 87.89844091258689,
 'frc3683': 96.15532416530903}

In [8]:
list1 = []
for i in tba.event_matches(event):
    if i['comp_level'] == 'qm':
        teamb1 = i['alliances']['blue']['team_keys'][0]
        teamb2 = i['alliances']['blue']['team_keys'][1]
        teamb3 = i['alliances']['blue']['team_keys'][2]
        teamr1 = i['alliances']['red']['team_keys'][0]
        teamr2 = i['alliances']['red']['team_keys'][1]
        teamr3 = i['alliances']['red']['team_keys'][2]
        
        foulb1 = i['score_breakdown']['red']['foulPoints']
        foulb2 = i['score_breakdown']['red']['foulPoints']
        foulb3 = i['score_breakdown']['red']['foulPoints']
        foulr1 = i['score_breakdown']['blue']['foulPoints']
        foulr2 = i['score_breakdown']['blue']['foulPoints']
        foulr3 = i['score_breakdown']['blue']['foulPoints']
        
        dict1 = { teamb1:foulb1
                , teamb2:foulb2
                , teamb3:foulb3
                , teamr1:foulr1
                , teamr2:foulr2
                , teamr3:foulr3}
        list1.append(dict1)
counter = collections.Counter()
for d in list1:
    counter.update(d)

res = dict(sorted(counter.items(), key=lambda item: item[1], reverse=True))

print('Top 3 Foul Points Given')
res

Top 3 Foul Points Given

{'frc9659': 94,
 'frc7757': 62,
 'frc8884': 60,
 'frc1325': 58,
 'frc7475': 58,
 'frc3739': 54,
 'frc5031': 54,
 'frc7136': 50,
 'frc771': 46,
 'frc4940': 46,
 'frc2634': 44,
 'frc3683': 44,
 'frc865': 42,
 'frc10027': 42,
 'frc10554': 42,
 'frc9263': 40,
 'frc5024': 40,
 'frc7558': 38,
 'frc2935': 36,
 'frc9785': 36,
 'frc8349': 36,
 'frc10167': 36,
 'frc2708': 34,
 'frc5719': 32,
 'frc8731': 32,
 'frc10218': 32,
 'frc10015': 30,
 'frc6632': 30,
 'frc2198': 28,
 'frc1241': 28,
 'frc2852': 28,
 'frc4476': 28,
 'frc7520': 26,
 'frc4907': 26,
 'frc1360': 26,
 'frc5912': 24,
 'frc1285': 24,
 'frc1305': 22,
 'frc6110': 20,
 'frc4152': 18,
 'frc6135': 16,
 'frc7659': 16,
 'frc7058': 16,
 'frc9262': 14,
 'frc2706': 14,
 'frc4039': 14,
 'frc5036': 14,
 'frc8089': 14,
 'frc9525': 12,
 'frc5032': 10}

In [9]:
print('Last 3 Picks')
print(tba.event_alliances(event)[0]['picks'][2])
print(tba.event_alliances(event)[1]['picks'][2])
print(tba.event_alliances(event)[2]['picks'][2])

Last 3 Picks
frc5036
frc5032
frc1285

In [10]:
dict1 = {}
for r in tba.event_rankings(event)['rankings']:
    team_key = r['team_key']
    dict1[team_key] = r['extra_stats'][0] - (3*r['record']['wins'])

res = dict(sorted(counter.items(), key=lambda item: item[1], reverse=True))

print('6th Highest Ranking Score (excluding Wins)')
print(sorted(dict1.items(), key=lambda x:x[1], reverse=True)[5])
print(sorted(dict1.items(), key=lambda x:x[1], reverse=True))

6th Highest Ranking Score (excluding Wins)
('frc1325', 30)
[('frc4039', 35), ('frc7558', 32), ('frc8884', 31), ('frc1241', 30), ('frc3683', 30), ('frc1325', 30), ('frc4907', 29), ('frc8089', 29), ('frc4476', 27), ('frc4940', 27), ('frc4152', 27), ('frc8349', 26), ('frc9785', 25), ('frc5024', 25), ('frc2708', 25), ('frc5036', 25), ('frc865', 24), ('frc1360', 24), ('frc7520', 23), ('frc2198', 23), ('frc6632', 23), ('frc7659', 23), ('frc9525', 22), ('frc3739', 22), ('frc9659', 22), ('frc7475', 22), ('frc10554', 21), ('frc10167', 21), ('frc6110', 21), ('frc5031', 20), ('frc2935', 20), ('frc5032', 20), ('frc1285', 20), ('frc10015', 20), ('frc10218', 20), ('frc1305', 19), ('frc7058', 19), ('frc9262', 19), ('frc6135', 19), ('frc2634', 17), ('frc8731', 17), ('frc5912', 16), ('frc9263', 16), ('frc2852', 16), ('frc5719', 15), ('frc2706', 14), ('frc7136', 13), ('frc10027', 13), ('frc771', 12), ('frc7757', 12)]

In [11]:
list1 = []

for t in teams:
    data = sb.get_team_event(t,event)['epa']
    diff = data['breakdown']['total_points'] - data['stats']['start']
    dict1 = {t:diff}
    list1.append(dict1)

counter = collections.Counter()
for d in list1:
    counter.update(d)
    
res = dict(sorted(counter.items(), key=lambda item: item[1], reverse=True))

print('Biggest EPA Gain')
res

Biggest EPA Gain

{9785: 21.39,
 1325: 18.979999999999997,
 2198: 15.829999999999998,
 1241: 13.900000000000006,
 7558: 13.380000000000003,
 8089: 13.040000000000003,
 4907: 12.599999999999994,
 8884: 12.009999999999991,
 3739: 10.899999999999999,
 865: 10.479999999999997,
 9525: 10.25,
 6110: 9.61,
 4152: 9.369999999999997,
 8349: 8.95,
 5032: 8.840000000000003,
 5024: 8.82,
 4039: 8.259999999999998,
 4940: 7.090000000000003,
 10554: 7.020000000000003,
 7520: 6.899999999999999,
 2634: 6.390000000000001,
 10015: 6.159999999999998,
 9659: 5.740000000000002,
 2708: 5.650000000000002,
 7058: 5.510000000000002,
 7659: 5.069999999999997,
 1305: 5.040000000000003,
 1360: 4.969999999999999,
 4476: 4.890000000000001,
 9262: 4.48,
 10167: 4.470000000000002,
 6632: 3.969999999999999,
 3683: 3.9200000000000017,
 5912: 3.230000000000004,
 2935: 3.020000000000003,
 5036: 2.8500000000000014,
 9263: 2.7699999999999996,
 2852: 2.5700000000000003,
 2706: 2.5,
 6135: 2.0500000000000007,
 7475: 1.1500000000000021,
 1285: 1.0799999999999983,
 10218: 0.7199999999999989,
 10027: 0.6900000000000013,
 5031: 0.10999999999999943,
 771: -0.3800000000000008,
 7136: -1.25,
 8731: -1.8399999999999999,
 7757: -2.619999999999999,
 5719: -2.6900000000000013}

In [12]:
list1 = []
for i in tba.event_matches(event):
    if i['comp_level'] == 'qm':
        teamb1 = i['alliances']['blue']['team_keys'][0]
        teamb2 = i['alliances']['blue']['team_keys'][1]
        teamb3 = i['alliances']['blue']['team_keys'][2]
        teamr1 = i['alliances']['red']['team_keys'][0]
        teamr2 = i['alliances']['red']['team_keys'][1]
        teamr3 = i['alliances']['red']['team_keys'][2]
        

        foulb1 = i['score_breakdown']['red']['wallAlgaeCount']
        foulb2 = i['score_breakdown']['red']['wallAlgaeCount']
        foulb3 = i['score_breakdown']['red']['wallAlgaeCount']
        foulr1 = i['score_breakdown']['blue']['wallAlgaeCount']
        foulr2 = i['score_breakdown']['blue']['wallAlgaeCount']
        foulr3 = i['score_breakdown']['blue']['wallAlgaeCount']
        
        dict1 = { teamb1:foulb1
                , teamb2:foulb2
                , teamb3:foulb3
                , teamr1:foulr1
                , teamr2:foulr2
                , teamr3:foulr3}
        list1.append(dict1)
counter = collections.Counter()
for d in list1:
    counter.update(d)

res = dict(sorted(counter.items(), key=lambda item: item[1], reverse=True))

print('Biggest (Attempted) Baller (HP with the most attempts at net)')
res

Biggest (Attempted) Baller (HP with the most attempts at net)

{'frc7475': 35,
 'frc4152': 30,
 'frc4039': 29,
 'frc865': 29,
 'frc5912': 29,
 'frc7757': 28,
 'frc7659': 28,
 'frc5719': 27,
 'frc8349': 27,
 'frc10554': 27,
 'frc9262': 26,
 'frc8731': 26,
 'frc7520': 25,
 'frc10218': 25,
 'frc4907': 24,
 'frc10027': 24,
 'frc8089': 24,
 'frc9263': 23,
 'frc2198': 23,
 'frc7136': 23,
 'frc4940': 23,
 'frc1241': 22,
 'frc2708': 21,
 'frc3683': 21,
 'frc10167': 21,
 'frc7558': 21,
 'frc6135': 19,
 'frc3739': 19,
 'frc5024': 19,
 'frc5032': 19,
 'frc771': 19,
 'frc9525': 18,
 'frc7058': 18,
 'frc1285': 18,
 'frc1305': 17,
 'frc2634': 16,
 'frc2706': 16,
 'frc9659': 16,
 'frc5031': 16,
 'frc2852': 16,
 'frc6632': 16,
 'frc8884': 15,
 'frc1360': 15,
 'frc2935': 14,
 'frc6110': 14,
 'frc1325': 12,
 'frc10015': 12,
 'frc4476': 12,
 'frc9785': 10,
 'frc5036': 8}

In [13]:
list1 = []
for i in tba.event_matches(event):
    if i['comp_level'] == 'qm':
        teamb1 = i['alliances']['blue']['team_keys'][0]
        teamb2 = i['alliances']['blue']['team_keys'][1]
        teamb3 = i['alliances']['blue']['team_keys'][2]
        teamr1 = i['alliances']['red']['team_keys'][0]
        teamr2 = i['alliances']['red']['team_keys'][1]
        teamr3 = i['alliances']['red']['team_keys'][2]
        
        foulb1 = i['score_breakdown']['blue']['teleopReef']['trough'] + i['score_breakdown']['blue']['autoReef']['trough']
        foulb2 = i['score_breakdown']['blue']['teleopReef']['trough'] + i['score_breakdown']['blue']['autoReef']['trough']
        foulb3 = i['score_breakdown']['blue']['teleopReef']['trough'] + i['score_breakdown']['blue']['autoReef']['trough']
        foulr1 = i['score_breakdown']['red']['teleopReef']['trough'] + i['score_breakdown']['red']['autoReef']['trough']
        foulr2 = i['score_breakdown']['red']['teleopReef']['trough'] + i['score_breakdown']['red']['autoReef']['trough']
        foulr3 = i['score_breakdown']['red']['teleopReef']['trough'] + i['score_breakdown']['red']['autoReef']['trough']
        
        dict1 = { teamb1:foulb1
                , teamb2:foulb2
                , teamb3:foulb3
                , teamr1:foulr1
                , teamr2:foulr2
                , teamr3:foulr3}
        list1.append(dict1)
counter = collections.Counter()
for d in list1:
    counter.update(d)

res = dict(sorted(counter.items(), key=lambda item: item[1], reverse=True))

print('Level 1 Demon')
res

Level 1 Demon

{'frc10167': 102,
 'frc4476': 75,
 'frc1241': 72,
 'frc7659': 67,
 'frc9525': 65,
 'frc8884': 64,
 'frc5031': 62,
 'frc10015': 60,
 'frc10218': 58,
 'frc4940': 56,
 'frc3683': 53,
 'frc4039': 49,
 'frc1325': 49,
 'frc9785': 47,
 'frc8089': 46,
 'frc6110': 45,
 'frc7058': 44,
 'frc9659': 43,
 'frc3739': 42,
 'frc2634': 41,
 'frc8731': 41,
 'frc8349': 41,
 'frc10027': 41,
 'frc10554': 41,
 'frc7558': 41,
 'frc2708': 40,
 'frc1305': 40,
 'frc4907': 39,
 'frc2935': 38,
 'frc5024': 38,
 'frc7136': 38,
 'frc7475': 38,
 'frc6135': 37,
 'frc5912': 36,
 'frc7520': 35,
 'frc6632': 35,
 'frc4152': 34,
 'frc1360': 33,
 'frc5032': 32,
 'frc5036': 31,
 'frc2706': 30,
 'frc771': 30,
 'frc1285': 29,
 'frc9262': 28,
 'frc2198': 26,
 'frc9263': 23,
 'frc7757': 23,
 'frc865': 22,
 'frc5719': 21,
 'frc2852': 15}

In [14]:
list1 = []
for i in tba.event_matches(event):
    if i['comp_level'] == 'qm':
        teamb1 = i['alliances']['blue']['team_keys'][0]
        teamb2 = i['alliances']['blue']['team_keys'][1]
        teamb3 = i['alliances']['blue']['team_keys'][2]
        teamr1 = i['alliances']['red']['team_keys'][0]
        teamr2 = i['alliances']['red']['team_keys'][1]
        teamr3 = i['alliances']['red']['team_keys'][2]
        

        foulb1 = 1 if i['score_breakdown']['blue']['autoBonusAchieved']*1 == 0 else 0
        foulb2 = 1 if i['score_breakdown']['blue']['autoBonusAchieved']*1 == 0 else 0
        foulb3 = 1 if i['score_breakdown']['blue']['autoBonusAchieved']*1 == 0 else 0
        foulr1 = 1 if i['score_breakdown']['red']['autoBonusAchieved']*1 == 0 else 0
        foulr2 = 1 if i['score_breakdown']['red']['autoBonusAchieved']*1 == 0 else 0
        foulr3 = 1 if i['score_breakdown']['red']['autoBonusAchieved']*1 == 0 else 0
        
        dict1 = { teamb1:foulb1
                , teamb2:foulb2
                , teamb3:foulb3
                , teamr1:foulr1
                , teamr2:foulr2
                , teamr3:foulr3}
        list1.append(dict1)
counter = collections.Counter()
for d in list1:
    counter.update(d)

res = dict(sorted(counter.items(), key=lambda item: item[1], reverse=True))

print('Most missed auto RP')
res

Most missed auto RP

{'frc5719': 6,
 'frc771': 6,
 'frc7757': 5,
 'frc8731': 5,
 'frc2706': 4,
 'frc10027': 4,
 'frc9262': 3,
 'frc9263': 3,
 'frc7659': 3,
 'frc2852': 3,
 'frc7136': 3,
 'frc2634': 2,
 'frc2935': 2,
 'frc6110': 2,
 'frc9659': 2,
 'frc5031': 2,
 'frc5036': 2,
 'frc8349': 2,
 'frc4152': 2,
 'frc10015': 2,
 'frc5032': 2,
 'frc6632': 2,
 'frc5912': 2,
 'frc7475': 2,
 'frc9525': 1,
 'frc6135': 1,
 'frc2708': 1,
 'frc7520': 1,
 'frc3739': 1,
 'frc1305': 1,
 'frc9785': 1,
 'frc3683': 1,
 'frc865': 1,
 'frc2198': 1,
 'frc1241': 1,
 'frc5024': 1,
 'frc1325': 1,
 'frc10218': 1,
 'frc10554': 1,
 'frc7058': 1,
 'frc10167': 1,
 'frc1285': 1,
 'frc4940': 1,
 'frc8884': 0,
 'frc4907': 0,
 'frc4039': 0,
 'frc1360': 0,
 'frc8089': 0,
 'frc4476': 0,
 'frc7558': 0}

In [15]:
list1 = []
list2 = []
dict3 = {}
for i in tba.event_matches(event):
    if i['comp_level'] == 'qm':
        teamb1 = i['alliances']['blue']['team_keys'][0]
        teamb2 = i['alliances']['blue']['team_keys'][1]
        teamb3 = i['alliances']['blue']['team_keys'][2]
        teamr1 = i['alliances']['red']['team_keys'][0]
        teamr2 = i['alliances']['red']['team_keys'][1]
        teamr3 = i['alliances']['red']['team_keys'][2]
        
        l1b1 = i['score_breakdown']['blue']['teleopReef']['trough']
        l1b2 = i['score_breakdown']['blue']['teleopReef']['trough']
        l1b3 = i['score_breakdown']['blue']['teleopReef']['trough']
        l1r1 = i['score_breakdown']['red']['teleopReef']['trough']
        l1r2 = i['score_breakdown']['red']['teleopReef']['trough']
        l1r3 = i['score_breakdown']['red']['teleopReef']['trough']
        
        l4b1 = i['score_breakdown']['blue']['teleopReef']['tba_topRowCount']
        l4b2 = i['score_breakdown']['blue']['teleopReef']['tba_topRowCount']
        l4b3 = i['score_breakdown']['blue']['teleopReef']['tba_topRowCount']
        l4r1 = i['score_breakdown']['red']['teleopReef']['tba_topRowCount']
        l4r2 = i['score_breakdown']['red']['teleopReef']['tba_topRowCount']
        l4r3 = i['score_breakdown']['red']['teleopReef']['tba_topRowCount']
        
        dict1 = { teamb1:l1b1
                , teamb2:l1b2
                , teamb3:l1b3
                , teamr1:l1r1
                , teamr2:l1r2
                , teamr3:l1r3}
        list1.append(dict1)
        
        dict2 = { teamb1:l4b1
                , teamb2:l4b2
                , teamb3:l4b3
                , teamr1:l4r1
                , teamr2:l4r2
                , teamr3:l4r3}
        list2.append(dict2)
        
        
counter1 = collections.Counter()
for d in list1:
    counter1.update(d)
    
        
counter2 = collections.Counter()
for d in list2:
    counter2.update(d)

for key in counter1:
    dict3[key] = counter2[key]/counter1[key]

res = dict(sorted(dict3.items(), key=lambda item: item[1], reverse=True))

print('Highest Level 4 to Level 1 Ratio')
res

Highest Level 4 to Level 1 Ratio

{'frc2852': 8.083333333333334,
 'frc865': 7.5625,
 'frc9263': 5.388888888888889,
 'frc1360': 4.482758620689655,
 'frc2706': 4.384615384615385,
 'frc2198': 4.375,
 'frc1285': 4.296296296296297,
 'frc4907': 4.0606060606060606,
 'frc4152': 4.0,
 'frc7520': 3.933333333333333,
 'frc2935': 3.735294117647059,
 'frc9262': 3.72,
 'frc5032': 3.4782608695652173,
 'frc7757': 3.3333333333333335,
 'frc5912': 3.3333333333333335,
 'frc7558': 3.3333333333333335,
 'frc771': 3.230769230769231,
 'frc6632': 3.225806451612903,
 'frc9659': 3.185185185185185,
 'frc1305': 3.1515151515151514,
 'frc2634': 3.1142857142857143,
 'frc7475': 3.09375,
 'frc3739': 3.0285714285714285,
 'frc5036': 2.962962962962963,
 'frc5024': 2.942857142857143,
 'frc7058': 2.9310344827586206,
 'frc5719': 2.888888888888889,
 'frc9785': 2.8095238095238093,
 'frc10554': 2.78125,
 'frc2708': 2.696969696969697,
 'frc3683': 2.5510204081632653,
 'frc1325': 2.533333333333333,
 'frc4039': 2.477272727272727,
 'frc10027': 2.4594594594594597,
 'frc7136': 2.25,
 'frc8089': 2.1818181818181817,
 'frc8884': 2.1724137931034484,
 'frc6135': 2.096774193548387,
 'frc4940': 1.9565217391304348,
 'frc8349': 1.945945945945946,
 'frc1241': 1.8,
 'frc9525': 1.7321428571428572,
 'frc10015': 1.7169811320754718,
 'frc5031': 1.6956521739130435,
 'frc6110': 1.6216216216216217,
 'frc8731': 1.6216216216216217,
 'frc4476': 1.606060606060606,
 'frc10218': 1.4186046511627908,
 'frc7659': 1.34375,
 'frc10167': 0.9310344827586207}

In [16]:
list1 = []
for i in tba.event_matches(event):
    if i['comp_level'] == 'qm':
        teamb1 = i['alliances']['blue']['team_keys'][0]
        teamb2 = i['alliances']['blue']['team_keys'][1]
        teamb3 = i['alliances']['blue']['team_keys'][2]
        teamr1 = i['alliances']['red']['team_keys'][0]
        teamr2 = i['alliances']['red']['team_keys'][1]
        teamr3 = i['alliances']['red']['team_keys'][2]
        
        foulb1 = i['score_breakdown']['blue']['netAlgaeCount']
        foulb2 = i['score_breakdown']['blue']['netAlgaeCount']
        foulb3 = i['score_breakdown']['blue']['netAlgaeCount']
        foulr1 = i['score_breakdown']['red']['netAlgaeCount']
        foulr2 = i['score_breakdown']['red']['netAlgaeCount']
        foulr3 = i['score_breakdown']['red']['netAlgaeCount']
        
        dict1 = { teamb1:foulb1
                , teamb2:foulb2
                , teamb3:foulb3
                , teamr1:foulr1
                , teamr2:foulr2
                , teamr3:foulr3}
        list1.append(dict1)
counter = collections.Counter()
for d in list1:
    counter.update(d)

res = dict(sorted(counter.items(), key=lambda item: item[1]))

print('Shittiest Fisherman (Most Empty Net)')
res

Shittiest Fisherman (Most Empty Net)

{'frc5036': 16,
 'frc5031': 21,
 'frc2706': 23,
 'frc9659': 23,
 'frc1360': 23,
 'frc6135': 24,
 'frc6632': 25,
 'frc771': 25,
 'frc10167': 25,
 'frc5719': 26,
 'frc3739': 26,
 'frc6110': 26,
 'frc4940': 26,
 'frc2935': 27,
 'frc8884': 28,
 'frc1305': 28,
 'frc10015': 28,
 'frc7136': 28,
 'frc10027': 29,
 'frc7058': 29,
 'frc4039': 30,
 'frc5912': 30,
 'frc9525': 31,
 'frc2852': 31,
 'frc2708': 32,
 'frc7757': 32,
 'frc10218': 32,
 'frc2634': 33,
 'frc9785': 33,
 'frc2198': 33,
 'frc8349': 33,
 'frc7520': 34,
 'frc5024': 34,
 'frc7659': 34,
 'frc5032': 34,
 'frc8731': 35,
 'frc9262': 36,
 'frc1285': 37,
 'frc865': 41,
 'frc7475': 41,
 'frc9263': 42,
 'frc10554': 45,
 'frc7558': 46,
 'frc4476': 48,
 'frc1241': 49,
 'frc1325': 52,
 'frc4907': 57,
 'frc4152': 58,
 'frc8089': 69,
 'frc3683': 77}

In [17]:
list1 = []
for i in tba.event_matches(event):
    if i['comp_level'] == 'qm':
        teamb1 = i['alliances']['blue']['team_keys'][0]
        teamb2 = i['alliances']['blue']['team_keys'][1]
        teamb3 = i['alliances']['blue']['team_keys'][2]
        teamr1 = i['alliances']['red']['team_keys'][0]
        teamr2 = i['alliances']['red']['team_keys'][1]
        teamr3 = i['alliances']['red']['team_keys'][2]
        
        bluepark = (1 if i['score_breakdown']['blue']['endGameRobot1'] == 'Parked' else 0) + (1 if i['score_breakdown']['blue']['endGameRobot2'] == 'Parked' else 0) + (1 if i['score_breakdown']['blue']['endGameRobot3'] == 'Parked' else 0)
        redpark = (1 if i['score_breakdown']['red']['endGameRobot1'] == 'Parked' else 0) + (1 if i['score_breakdown']['red']['endGameRobot2'] == 'Parked' else 0) + (1 if i['score_breakdown']['red']['endGameRobot3'] == 'Parked' else 0)

        dict1 = { teamb1:bluepark
                , teamb2:bluepark
                , teamb3:bluepark
                , teamr1:redpark
                , teamr2:redpark
                , teamr3:redpark}
        list1.append(dict1)
counter = collections.Counter()
for d in list1:
    counter.update(d)

res = dict(sorted(counter.items(), key=lambda item: item[1], reverse=True))

print('Shipwrecks (Most Alliance Parks)')
res

Shipwrecks (Most Alliance Parks)

{'frc7757': 25,
 'frc9785': 25,
 'frc5024': 25,
 'frc10554': 25,
 'frc5031': 24,
 'frc7475': 24,
 'frc2706': 23,
 'frc10015': 23,
 'frc10218': 23,
 'frc7136': 23,
 'frc7520': 22,
 'frc6110': 22,
 'frc8731': 22,
 'frc1241': 22,
 'frc7058': 22,
 'frc9525': 21,
 'frc2708': 21,
 'frc9659': 21,
 'frc5032': 21,
 'frc4476': 21,
 'frc8884': 20,
 'frc5719': 20,
 'frc2935': 20,
 'frc2198': 20,
 'frc8349': 20,
 'frc2852': 20,
 'frc771': 20,
 'frc8089': 20,
 'frc2634': 19,
 'frc3739': 19,
 'frc865': 19,
 'frc10027': 19,
 'frc10167': 19,
 'frc9262': 18,
 'frc9263': 18,
 'frc3683': 18,
 'frc6632': 18,
 'frc4940': 18,
 'frc1360': 17,
 'frc1325': 16,
 'frc7558': 16,
 'frc4907': 15,
 'frc4152': 15,
 'frc5912': 15,
 'frc4039': 14,
 'frc5036': 14,
 'frc1285': 14,
 'frc1305': 13,
 'frc6135': 12,
 'frc7659': 11}

In [18]:
list1 = []
for i in tba.event_matches(event):
    if i['comp_level'] == 'qm':
        teamb1 = i['alliances']['blue']['team_keys'][0]
        teamb2 = i['alliances']['blue']['team_keys'][1]
        teamb3 = i['alliances']['blue']['team_keys'][2]
        teamr1 = i['alliances']['red']['team_keys'][0]
        teamr2 = i['alliances']['red']['team_keys'][1]
        teamr3 = i['alliances']['red']['team_keys'][2]
        
        bluel1 = max(0,-1*i['score_breakdown']['blue']['teleopReef']['trough'])
        bluel2 = 0
        bluel3 = 0
        bluel4 = 0
        redl1 = max(0,-1*i['score_breakdown']['red']['teleopReef']['trough'])
        redl2 = 0
        redl3 = 0
        redl4 = 0
        
        for j in i['score_breakdown']['blue']['autoReef']['botRow'].items():
            bluel2 += 1 if 1*j[1] > 1*i['score_breakdown']['blue']['teleopReef']['botRow'][j[0]] else 0
        for j in i['score_breakdown']['blue']['autoReef']['midRow'].items():
            bluel3 += 1 if 1*j[1] > 1*i['score_breakdown']['blue']['teleopReef']['midRow'][j[0]] else 0
        for j in i['score_breakdown']['blue']['autoReef']['topRow'].items():
            bluel4 += 1 if 1*j[1] > 1*i['score_breakdown']['blue']['teleopReef']['topRow'][j[0]] else 0
            
        for j in i['score_breakdown']['red']['autoReef']['botRow'].items():
            redl2 += 1 if 1*j[1] > 1*i['score_breakdown']['red']['teleopReef']['botRow'][j[0]] else 0
        for j in i['score_breakdown']['red']['autoReef']['midRow'].items():
            redl3 += 1 if 1*j[1] > 1*i['score_breakdown']['red']['teleopReef']['midRow'][j[0]] else 0
        for j in i['score_breakdown']['red']['autoReef']['topRow'].items():
            redl4 += 1 if 1*j[1] > 1*i['score_breakdown']['red']['teleopReef']['topRow'][j[0]] else 0
        
        reddiff = redl1+redl2+redl3+redl4
        bluediff = bluel1+bluel2+bluel3+bluel4
        
        dict1 = { teamb1:bluediff
                , teamb2:bluediff
                , teamb3:bluediff
                , teamr1:reddiff
                , teamr2:reddiff
                , teamr3:reddiff}
        list1.append(dict1)
counter = collections.Counter()
for d in list1:
    counter.update(d)

res = dict(sorted(counter.items(), key=lambda item: item[1], reverse=True))

print('I did a bad (Descored coral in teleop that was scored in auto)')
res

I did a bad (Descored coral in teleop that was scored in auto)

{'frc9659': 2,
 'frc9263': 1,
 'frc2706': 1,
 'frc6110': 1,
 'frc5031': 1,
 'frc865': 1,
 'frc10218': 1,
 'frc1285': 1,
 'frc9262': 0,
 'frc9525': 0,
 'frc2634': 0,
 'frc6135': 0,
 'frc2708': 0,
 'frc8884': 0,
 'frc5719': 0,
 'frc2935': 0,
 'frc7757': 0,
 'frc7520': 0,
 'frc3739': 0,
 'frc1305': 0,
 'frc9785': 0,
 'frc3683': 0,
 'frc4907': 0,
 'frc4039': 0,
 'frc2198': 0,
 'frc8731': 0,
 'frc1241': 0,
 'frc5024': 0,
 'frc1325': 0,
 'frc5036': 0,
 'frc8349': 0,
 'frc7659': 0,
 'frc4152': 0,
 'frc10015': 0,
 'frc10027': 0,
 'frc1360': 0,
 'frc10554': 0,
 'frc5032': 0,
 'frc2852': 0,
 'frc6632': 0,
 'frc771': 0,
 'frc8089': 0,
 'frc7058': 0,
 'frc4476': 0,
 'frc5912': 0,
 'frc7136': 0,
 'frc10167': 0,
 'frc7558': 0,
 'frc7475': 0,
 'frc4940': 0}

In [19]:
# event = '2025iscmp'

val = 0
for i in tba.event_matches(event):
    if i['comp_level'] == 'qm':
        
        bluecoral = i['score_breakdown']['blue']['rp']
        redcoral = i['score_breakdown']['red']['rp'] 

        if bluecoral + redcoral == 9:
            val += 1
        
val
# list1

# print('Shipwrecks (Most Alliance Parks)')
# res

7

In [20]:
botrow = 0
match = 20
print(tba.event_matches(event)[match]['key'])

bluel1 = max(0,-1*tba.event_matches(event)[match]['score_breakdown']['blue']['teleopReef']['trough'])
bluel2 = 0
bluel3 = 0
bluel4 = 0
redl1 = max(0,-1*tba.event_matches(event)[match]['score_breakdown']['red']['teleopReef']['trough'])
redl2 = 0
redl3 = 0
redl4 = 0

for i in tba.event_matches(event)[match]['score_breakdown']['blue']['autoReef']['botRow'].items():
    bluel2 += 1 if  1*i[1] > 1*tba.event_matches(event)[match]['score_breakdown']['blue']['teleopReef']['botRow'][i[0]] else 0
for i in tba.event_matches(event)[match]['score_breakdown']['blue']['autoReef']['midRow'].items():
    bluel3 += 1 if  1*i[1] > 1*tba.event_matches(event)[match]['score_breakdown']['blue']['teleopReef']['midRow'][i[0]] else 0
for i in tba.event_matches(event)[match]['score_breakdown']['blue']['autoReef']['topRow'].items():
    bluel4 += 1 if  1*i[1] > 1*tba.event_matches(event)[match]['score_breakdown']['blue']['teleopReef']['topRow'][i[0]] else 0
    
for i in tba.event_matches(event)[match]['score_breakdown']['red']['autoReef']['botRow'].items():
    redl2 += 1 if  1*i[1] > 1*tba.event_matches(event)[match]['score_breakdown']['red']['teleopReef']['botRow'][i[0]] else 0
for i in tba.event_matches(event)[match]['score_breakdown']['red']['autoReef']['midRow'].items():
    redl3 += 1 if  1*i[1] > 1*tba.event_matches(event)[match]['score_breakdown']['red']['teleopReef']['midRow'][i[0]] else 0
for i in tba.event_matches(event)[match]['score_breakdown']['red']['autoReef']['topRow'].items():
    redl4 += 1 if  1*i[1] > 1*tba.event_matches(event)[match]['score_breakdown']['red']['teleopReef']['topRow'][i[0]] else 0
    
reddiff = redl1+redl2+redl3+redl4
bluediff = bluel1+bluel2+bluel3+bluel4

print(reddiff, bluediff)

#12, 20, 31,45

2025oncmp1_qm24
0 0

In [21]:
event = '2025onham'

list1 = []
for i in tba.event_matches(event):
    if i['comp_level'] == 'qm':
        
#         bluecoral = 1 if (i['score_breakdown']['blue']['teleopReef']['trough'] + i['score_breakdown']['blue']['autoReef']['trough']) > 1 else 0
#         redcoral = 1 if (i['score_breakdown']['red']['teleopReef']['trough'] + i['score_breakdown']['red']['autoReef']['trough']) > 1 else 0

        bluecoral = i['score_breakdown']['blue']['autoMobilityPoints'] 
        redcoral = i['score_breakdown']['red']['autoMobilityPoints']

        list1 += [bluecoral, redcoral]
        
sum(list1) / len(list1)
# list1

# print('Shipwrecks (Most Alliance Parks)')
# res

8.346774193548388

In [67]:
tba.event_matches(event)[38]

Match({'actual_time': 1743710601, 'alliances': {'blue': {'dq_team_keys': [], 'score': 102, 'surrogate_team_keys': [], 'team_keys': ['frc8089', 'frc2852', 'frc2634']}, 'red': {'dq_team_keys': [], 'score': 181, 'surrogate_team_keys': [], 'team_keys': ['frc1325', 'frc7757', 'frc2935']}}, 'comp_level': 'qm', 'event_key': '2025oncmp1', 'key': '2025oncmp1_qm40', 'match_number': 40, 'post_result_time': 1743710827, 'predicted_time': 1743710614, 'score_breakdown': {'blue': {'adjustPoints': 0, 'algaePoints': 46, 'autoBonusAchieved': True, 'autoCoralCount': 1, 'autoCoralPoints': 3, 'autoLineRobot1': 'Yes', 'autoLineRobot2': 'Yes', 'autoLineRobot3': 'Yes', 'autoMobilityPoints': 9, 'autoPoints': 12, 'autoReef': {'botRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'midRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'tba_botRowCount': 0, 'tba_midRowCount': 0, 'tba_topRowCount': 0, 'topRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'trough': 1}, 'bargeBonusAchieved': True, 'coopertitionCriteriaMet': True, 'coralBonusAchieved': False, 'endGameBargePoints': 14, 'endGameRobot1': 'DeepCage', 'endGameRobot2': 'Parked', 'endGameRobot3': 'None', 'foulCount': 0, 'foulPoints': 0, 'g206Penalty': False, 'g410Penalty': False, 'g418Penalty': False, 'g428Penalty': False, 'netAlgaeCount': 7, 'rp': 2, 'techFoulCount': 0, 'teleopCoralCount': 6, 'teleopCoralPoints': 30, 'teleopPoints': 90, 'teleopReef': {'botRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'midRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'tba_botRowCount': 0, 'tba_midRowCount': 0, 'tba_topRowCount': 6, 'topRow': {'nodeA': True, 'nodeB': True, 'nodeC': True, 'nodeD': True, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': True, 'nodeL': True}, 'trough': 0}, 'totalPoints': 102, 'wallAlgaeCount': 3}, 'red': {'adjustPoints': 0, 'algaePoints': 36, 'autoBonusAchieved': True, 'autoCoralCount': 3, 'autoCoralPoints': 21, 'autoLineRobot1': 'Yes', 'autoLineRobot2': 'Yes', 'autoLineRobot3': 'Yes', 'autoMobilityPoints': 9, 'autoPoints': 30, 'autoReef': {'botRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'midRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': False, 'nodeK': False, 'nodeL': False}, 'tba_botRowCount': 0, 'tba_midRowCount': 0, 'tba_topRowCount': 3, 'topRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': False, 'nodeH': False, 'nodeI': False, 'nodeJ': True, 'nodeK': True, 'nodeL': True}, 'trough': 0}, 'bargeBonusAchieved': True, 'coopertitionCriteriaMet': True, 'coralBonusAchieved': True, 'endGameBargePoints': 14, 'endGameRobot1': 'DeepCage', 'endGameRobot2': 'None', 'endGameRobot3': 'Parked', 'foulCount': 0, 'foulPoints': 0, 'g206Penalty': False, 'g410Penalty': False, 'g418Penalty': False, 'g428Penalty': False, 'netAlgaeCount': 6, 'rp': 6, 'techFoulCount': 0, 'teleopCoralCount': 28, 'teleopCoralPoints': 101, 'teleopPoints': 151, 'teleopReef': {'botRow': {'nodeA': False, 'nodeB': False, 'nodeC': False, 'nodeD': False, 'nodeE': False, 'nodeF': False, 'nodeG': True, 'nodeH': False, 'nodeI': True, 'nodeJ': True, 'nodeK': True, 'nodeL': True}, 'midRow': {'nodeA': True, 'nodeB': True, 'nodeC': True, 'nodeD': True, 'nodeE': True, 'nodeF': True, 'nodeG': False, 'nodeH': True, 'nodeI': True, 'nodeJ': True, 'nodeK': True, 'nodeL': True}, 'tba_botRowCount': 5, 'tba_midRowCount': 11, 'tba_topRowCount': 11, 'topRow': {'nodeA': True, 'nodeB': True, 'nodeC': True, 'nodeD': True, 'nodeE': True, 'nodeF': True, 'nodeG': False, 'nodeH': True, 'nodeI': True, 'nodeJ': True, 'nodeK': True, 'nodeL': True}, 'trough': 1}, 'totalPoints': 181, 'wallAlgaeCount': 2}}, 'set_number': 1, 'time': 1743708120, 'videos': [{'key': 'VW4rTR8DASg', 'type': 'youtube'}, {'key': '18rQhegal1I', 'type': 'youtube'}], 'winning_alliance': 'red'})

In [23]:
list1 = []
for i in tba.event_matches('2025onosh'):
    if i['comp_level'] == 'qm':
        teamb1 = i['alliances']['blue']['team_keys'][0]
        teamb2 = i['alliances']['blue']['team_keys'][1]
        teamb3 = i['alliances']['blue']['team_keys'][2]
        teamr1 = i['alliances']['red']['team_keys'][0]
        teamr2 = i['alliances']['red']['team_keys'][1]
        teamr3 = i['alliances']['red']['team_keys'][2]
        
        foulb1 = i['score_breakdown']['blue']['teleopReef']['trough'] + i['score_breakdown']['blue']['autoReef']['trough']
        foulb2 = i['score_breakdown']['blue']['teleopReef']['trough'] + i['score_breakdown']['blue']['autoReef']['trough']
        foulb3 = i['score_breakdown']['blue']['teleopReef']['trough'] + i['score_breakdown']['blue']['autoReef']['trough']
        foulr1 = i['score_breakdown']['red']['teleopReef']['trough'] + i['score_breakdown']['red']['autoReef']['trough']
        foulr2 = i['score_breakdown']['red']['teleopReef']['trough'] + i['score_breakdown']['red']['autoReef']['trough']
        foulr3 = i['score_breakdown']['red']['teleopReef']['trough'] + i['score_breakdown']['red']['autoReef']['trough']
        
        dict1 = { teamb1:foulb1
                , teamb2:foulb2
                , teamb3:foulb3
                , teamr1:foulr1
                , teamr2:foulr2
                , teamr3:foulr3}
        list1.append(dict1)
counter = collections.Counter()
for d in list1:
    counter.update(d)

res = dict(sorted(counter.items(), key=lambda item: item[1], reverse=True))

print('Level 1 Demon')
res

Level 1 Demon

{'frc8764': 49,
 'frc8884': 44,
 'frc4476': 39,
 'frc9062': 38,
 'frc5870': 36,
 'frc4917': 36,
 'frc8729': 33,
 'frc2708': 32,
 'frc9580': 30,
 'frc5406': 28,
 'frc7902': 28,
 'frc5036': 26,
 'frc5031': 25,
 'frc9569': 24,
 'frc10279': 22,
 'frc7200': 22,
 'frc8731': 19,
 'frc8349': 19,
 'frc6864': 18,
 'frc6859': 17,
 'frc7480': 16,
 'frc10464': 16,
 'frc2198': 15,
 'frc7712': 13,
 'frc9592': 13,
 'frc4907': 12,
 'frc2852': 12,
 'frc10015': 11,
 'frc9589': 10,
 'frc5596': 10,
 'frc3543': 10}

In [24]:
sb.get_match('2025oncmp2_qm7')

{'key': '2025oncmp2_qm7',
 'year': 2025,
 'event': '2025oncmp2',
 'week': 6,
 'elim': False,
 'comp_level': 'qm',
 'set_number': 1,
 'match_number': 7,
 'match_name': 'Qual 7',
 'time': 1743688440,
 'predicted_time': 1743689068,
 'status': 'Completed',
 'video': 'CKG7EQyHtGU',
 'alliances': {'red': {'team_keys': [3756, 8729, 1310],
   'surrogate_team_keys': [],
   'dq_team_keys': []},
  'blue': {'team_keys': [9098, 2702, 6978],
   'surrogate_team_keys': [],
   'dq_team_keys': []}},
 'pred': {'winner': 'blue',
  'red_win_prob': 0.158,
  'red_score': 108.06,
  'blue_score': 153.1,
  'red_auto_rp': 0.4023,
  'blue_auto_rp': 0.8796,
  'red_coral_rp': 0.0721,
  'blue_coral_rp': 0.1846,
  'red_barge_rp': 0.5593,
  'blue_barge_rp': 0.8639,
  'red_rp_1': 0.4023,
  'blue_rp_1': 0.8796,
  'red_rp_2': 0.0721,
  'blue_rp_2': 0.1846,
  'red_rp_3': 0.5593,
  'blue_rp_3': 0.8639},
 'result': {'winner': 'tie',
  'red_score': 165,
  'blue_score': 165,
  'red_no_foul': 159,
  'blue_no_foul': 165,
  'red_auto_points': 30,
  'blue_auto_points': 37,
  'red_teleop_points': 103,
  'blue_teleop_points': 112,
  'red_endgame_points': 26,
  'blue_endgame_points': 16,
  'red_auto_rp': True,
  'blue_auto_rp': True,
  'red_coral_rp': False,
  'blue_coral_rp': True,
  'red_barge_rp': True,
  'blue_barge_rp': True,
  'red_tiebreaker_points': 0,
  'blue_tiebreaker_points': 0,
  'red_auto_leave_points': 9.0,
  'blue_auto_leave_points': 9.0,
  'red_auto_coral': 3.0,
  'blue_auto_coral': 4.0,
  'red_auto_coral_points': 21.0,
  'blue_auto_coral_points': 28.0,
  'red_teleop_coral': 20.0,
  'blue_teleop_coral': 28.0,
  'red_teleop_coral_points': 73.0,
  'blue_teleop_coral_points': 88.0,
  'red_coral_l1': 1.0,
  'blue_coral_l1': 5.0,
  'red_coral_l2': 2.0,
  'blue_coral_l2': 5.0,
  'red_coral_l3': 5.0,
  'blue_coral_l3': 7.0,
  'red_coral_l4': 12.0,
  'blue_coral_l4': 11.0,
  'red_total_coral_points': 94.0,
  'blue_total_coral_points': 116.0,
  'red_processor_algae': 5.0,
  'blue_processor_algae': 0.0,
  'red_processor_algae_points': 30.0,
  'blue_processor_algae_points': 0.0,
  'red_net_algae': 0.0,
  'blue_net_algae': 6.0,
  'red_net_algae_points': 0.0,
  'blue_net_algae_points': 24.0,
  'red_total_algae_points': 30.0,
  'blue_total_algae_points': 24.0,
  'red_total_game_pieces': 25.0,
  'blue_total_game_pieces': 34.0,
  'red_barge_points': 26.0,
  'blue_barge_points': 16.0,
  'red_rp_1': True,
  'blue_rp_1': True,
  'red_rp_2': False,
  'blue_rp_2': True,
  'red_rp_3': True,
  'blue_rp_3': True}}

In [30]:
tba.event_matches(event)[20]['alliances'][tba.event_matches(event)[20]['winning_alliance']]['score']

99

In [53]:
event1 = '2025oncmp1'
event2 = '2025oncmp2'
events = [event1, event2]

In [78]:
print('High Score Changes')
for e in events:
    count_ = 0
    score_ = 0
    for i in tba.event_matches(e):
        if i['comp_level'] == 'qm':
            winning_alliance = 'red' if i['winning_alliance'] == '' else i['winning_alliance']
            if i['alliances'][winning_alliance]['score'] > score_:
                count_ += 1
                score_ = i['alliances'][winning_alliance]['score']
                
    print(count_-1)

High Score Changes
6
4

In [56]:
print('9 RP Matches')
for e in events:
    val = 0
    for i in tba.event_matches(e):
        if i['comp_level'] == 'qm':
            
            bluecoral = i['score_breakdown']['blue']['rp']
            redcoral = i['score_breakdown']['red']['rp'] 
    
            if bluecoral + redcoral == 9:
                val += 1
            
    print(val)

9 RP Matches
7
12

In [59]:
print('Matches with at least 1 L1')
for e in events:
    count_ = 0
    score_ = 0
    for i in tba.event_matches(e):
        if i['comp_level'] == 'qm':
            blue = 1 if i['score_breakdown']['blue']['teleopReef']['trough'] + i['score_breakdown']['blue']['autoReef']['trough'] > 0 else 0
            red = 1 if i['score_breakdown']['red']['teleopReef']['trough'] + i['score_breakdown']['red']['autoReef']['trough'] > 0 else 0
            count_ += 2
            score_ += blue + red
    print(score_, count_)

Matches with at least 1 L1
164 200
173 200

In [63]:
print('Avg Leave Points')
for e in events:
    count_ = 0
    score_ = 0
    for i in tba.event_matches(e):
        if i['comp_level'] == 'qm':
            
            blue = i['score_breakdown']['blue']['autoMobilityPoints'] 
            red = i['score_breakdown']['red']['autoMobilityPoints']
    
            count_ += 1
            score_ += blue + red
            
    print(score_, count_)

Avg Leave Points
1758 100
1740 100

In [64]:
print('Foul Points')
for e in events:
    count_ = 0
    score_ = 0
    for i in tba.event_matches(e):
        if i['comp_level'] == 'qm':
            
            blue = i['score_breakdown']['blue']['foulPoints'] 
            red = i['score_breakdown']['red']['foulPoints']
    
            count_ += 2
            score_ += blue + red
            
    print(e, score_, count_)

Foul Points
2025oncmp1 562 200
2025oncmp2 500 200

In [69]:
print('Foul Points')
for e in events:
    count_ = 0
    L2 = 0
    L3 = 0
    for i in tba.event_matches(e):
        if i['comp_level'] == 'qm':
            
            blueL2 = i['score_breakdown']['blue']['teleopReef']['tba_botRowCount']
            redL2 = i['score_breakdown']['red']['teleopReef']['tba_botRowCount']
            blueL3 = i['score_breakdown']['blue']['teleopReef']['tba_midRowCount']
            redL3 = i['score_breakdown']['red']['teleopReef']['tba_midRowCount']
    
            count_ += 2
            L2 += blueL2 + redL2
            L3 += blueL3 + redL3
            
    print(e, L2/L3, count_)

Foul Points
2025oncmp1 0.6349466776045939 200
2025oncmp2 0.655794587092297 200

In [74]:
print('Most Popular Branch')
for e in events:
    count_ = 0
    branchA = 0
    branchB = 0
    branchC = 0
    branchD = 0
    branchE = 0
    branchF = 0
    branchG = 0
    branchH = 0
    branchI = 0
    branchJ = 0
    branchK = 0
    branchL = 0
    for i in tba.event_matches(e):
        if i['comp_level'] == 'qm':
            for r in ['botRow', 'midRow', 'topRow']:
                branchA += i['score_breakdown']['blue']['teleopReef'][r]['nodeA'] + i['score_breakdown']['red']['teleopReef'][r]['nodeA']
                branchB += i['score_breakdown']['blue']['teleopReef'][r]['nodeB'] + i['score_breakdown']['red']['teleopReef'][r]['nodeB']
                branchC += i['score_breakdown']['blue']['teleopReef'][r]['nodeC'] + i['score_breakdown']['red']['teleopReef'][r]['nodeC']
                branchD += i['score_breakdown']['blue']['teleopReef'][r]['nodeD'] + i['score_breakdown']['red']['teleopReef'][r]['nodeD']
                branchE += i['score_breakdown']['blue']['teleopReef'][r]['nodeE'] + i['score_breakdown']['red']['teleopReef'][r]['nodeE']
                branchF += i['score_breakdown']['blue']['teleopReef'][r]['nodeF'] + i['score_breakdown']['red']['teleopReef'][r]['nodeF']
                branchG += i['score_breakdown']['blue']['teleopReef'][r]['nodeG'] + i['score_breakdown']['red']['teleopReef'][r]['nodeG']
                branchH += i['score_breakdown']['blue']['teleopReef'][r]['nodeH'] + i['score_breakdown']['red']['teleopReef'][r]['nodeH']
                branchI += i['score_breakdown']['blue']['teleopReef'][r]['nodeI'] + i['score_breakdown']['red']['teleopReef'][r]['nodeI']
                branchJ += i['score_breakdown']['blue']['teleopReef'][r]['nodeJ'] + i['score_breakdown']['red']['teleopReef'][r]['nodeJ']
                branchK += i['score_breakdown']['blue']['teleopReef'][r]['nodeK'] + i['score_breakdown']['red']['teleopReef'][r]['nodeK']
                branchL += i['score_breakdown']['blue']['teleopReef'][r]['nodeL'] + i['score_breakdown']['red']['teleopReef'][r]['nodeL']
            
            count_ += 2
            
    print(e, count_)
    print('A', branchA)
    print('B', branchB)
    print('C', branchC)
    print('D', branchD)
    print('E', branchE)
    print('F', branchF)
    print('G', branchG)
    print('H', branchH)
    print('I', branchI)
    print('J', branchJ)
    print('K', branchK)
    print('L', branchL)

Most Popular Branch
2025oncmp1 200
A 398
B 399
C 368
D 342
E 267
F 232
G 178
H 184
I 223
J 273
K 352
L 376
2025oncmp2 200
A 449
B 447
C 407
D 382
E 312
F 278
G 247
H 253
I 283
J 334
K 399
L 412

In [75]:
print('Most Popular L2 Branch')
for e in events:
    count_ = 0
    branchA = 0
    branchB = 0
    branchC = 0
    branchD = 0
    branchE = 0
    branchF = 0
    branchG = 0
    branchH = 0
    branchI = 0
    branchJ = 0
    branchK = 0
    branchL = 0
    for i in tba.event_matches(e):
        if i['comp_level'] == 'qm':
            for r in ['midRow']:
                branchA += i['score_breakdown']['blue']['teleopReef'][r]['nodeA'] + i['score_breakdown']['red']['teleopReef'][r]['nodeA']
                branchB += i['score_breakdown']['blue']['teleopReef'][r]['nodeB'] + i['score_breakdown']['red']['teleopReef'][r]['nodeB']
                branchC += i['score_breakdown']['blue']['teleopReef'][r]['nodeC'] + i['score_breakdown']['red']['teleopReef'][r]['nodeC']
                branchD += i['score_breakdown']['blue']['teleopReef'][r]['nodeD'] + i['score_breakdown']['red']['teleopReef'][r]['nodeD']
                branchE += i['score_breakdown']['blue']['teleopReef'][r]['nodeE'] + i['score_breakdown']['red']['teleopReef'][r]['nodeE']
                branchF += i['score_breakdown']['blue']['teleopReef'][r]['nodeF'] + i['score_breakdown']['red']['teleopReef'][r]['nodeF']
                branchG += i['score_breakdown']['blue']['teleopReef'][r]['nodeG'] + i['score_breakdown']['red']['teleopReef'][r]['nodeG']
                branchH += i['score_breakdown']['blue']['teleopReef'][r]['nodeH'] + i['score_breakdown']['red']['teleopReef'][r]['nodeH']
                branchI += i['score_breakdown']['blue']['teleopReef'][r]['nodeI'] + i['score_breakdown']['red']['teleopReef'][r]['nodeI']
                branchJ += i['score_breakdown']['blue']['teleopReef'][r]['nodeJ'] + i['score_breakdown']['red']['teleopReef'][r]['nodeJ']
                branchK += i['score_breakdown']['blue']['teleopReef'][r]['nodeK'] + i['score_breakdown']['red']['teleopReef'][r]['nodeK']
                branchL += i['score_breakdown']['blue']['teleopReef'][r]['nodeL'] + i['score_breakdown']['red']['teleopReef'][r]['nodeL']
            
            count_ += 2
            
    print(e, count_)
    print('A', branchA)
    print('B', branchB)
    print('C', branchC)
    print('D', branchD)
    print('E', branchE)
    print('F', branchF)
    print('G', branchG)
    print('H', branchH)
    print('I', branchI)
    print('J', branchJ)
    print('K', branchK)
    print('L', branchL)

Most Popular L2 Branch
2025oncmp1 200
A 131
B 132
C 133
D 126
E 85
F 75
G 52
H 55
I 77
J 81
K 135
L 137
2025oncmp2 200
A 148
B 152
C 144
D 136
E 112
F 98
G 84
H 87
I 103
J 103
K 138
L 136

In [76]:
print('Most Popular L4 Branch')
for e in events:
    count_ = 0
    branchA = 0
    branchB = 0
    branchC = 0
    branchD = 0
    branchE = 0
    branchF = 0
    branchG = 0
    branchH = 0
    branchI = 0
    branchJ = 0
    branchK = 0
    branchL = 0
    for i in tba.event_matches(e):
        if i['comp_level'] == 'qm':
            for r in ['topRow']:
                branchA += i['score_breakdown']['blue']['teleopReef'][r]['nodeA'] + i['score_breakdown']['red']['teleopReef'][r]['nodeA']
                branchB += i['score_breakdown']['blue']['teleopReef'][r]['nodeB'] + i['score_breakdown']['red']['teleopReef'][r]['nodeB']
                branchC += i['score_breakdown']['blue']['teleopReef'][r]['nodeC'] + i['score_breakdown']['red']['teleopReef'][r]['nodeC']
                branchD += i['score_breakdown']['blue']['teleopReef'][r]['nodeD'] + i['score_breakdown']['red']['teleopReef'][r]['nodeD']
                branchE += i['score_breakdown']['blue']['teleopReef'][r]['nodeE'] + i['score_breakdown']['red']['teleopReef'][r]['nodeE']
                branchF += i['score_breakdown']['blue']['teleopReef'][r]['nodeF'] + i['score_breakdown']['red']['teleopReef'][r]['nodeF']
                branchG += i['score_breakdown']['blue']['teleopReef'][r]['nodeG'] + i['score_breakdown']['red']['teleopReef'][r]['nodeG']
                branchH += i['score_breakdown']['blue']['teleopReef'][r]['nodeH'] + i['score_breakdown']['red']['teleopReef'][r]['nodeH']
                branchI += i['score_breakdown']['blue']['teleopReef'][r]['nodeI'] + i['score_breakdown']['red']['teleopReef'][r]['nodeI']
                branchJ += i['score_breakdown']['blue']['teleopReef'][r]['nodeJ'] + i['score_breakdown']['red']['teleopReef'][r]['nodeJ']
                branchK += i['score_breakdown']['blue']['teleopReef'][r]['nodeK'] + i['score_breakdown']['red']['teleopReef'][r]['nodeK']
                branchL += i['score_breakdown']['blue']['teleopReef'][r]['nodeL'] + i['score_breakdown']['red']['teleopReef'][r]['nodeL']
            
            count_ += 2
            
    print(e, count_)
    print('A', branchA)
    print('B', branchB)
    print('C', branchC)
    print('D', branchD)
    print('E', branchE)
    print('F', branchF)
    print('G', branchG)
    print('H', branchH)
    print('I', branchI)
    print('J', branchJ)
    print('K', branchK)
    print('L', branchL)

Most Popular L4 Branch
2025oncmp1 200
A 150
B 153
C 159
D 148
E 131
F 110
G 110
H 117
I 96
J 131
K 142
L 152
2025oncmp2 200
A 174
B 167
C 170
D 166
E 139
F 125
G 133
H 135
I 120
J 153
K 162
L 173

In [82]:
print('Matches decided by fouls')
for e in events:
    count_ = 0
    score_ = 0
    for i in tba.event_matches(e):
        if i['comp_level'] == 'qm':
            if i['alliances']['red']['score'] > i['alliances']['blue']['score']:
                if i['alliances']['red']['score'] - i['score_breakdown']['red']['foulPoints'] <= i['alliances']['blue']['score'] - i['score_breakdown']['blue']['foulPoints']:
                    score_ += 1
            elif i['alliances']['red']['score'] < i['alliances']['blue']['score']:
                if i['alliances']['red']['score'] - i['score_breakdown']['red']['foulPoints'] >= i['alliances']['blue']['score'] - i['score_breakdown']['blue']['foulPoints']:
                    score_ += 1
            else:
                if i['score_breakdown']['red']['foulPoints'] != i['score_breakdown']['blue']['foulPoints']:
                    score_ += 1
            count_ += 1
                
    print(e, score_, count_)

Matches decided by fouls
2025oncmp1 2 100
2025oncmp2 3 100

In [11]:
sb.get_team_year(teams[0], 2025)['epa']['stats']

{'start': 18.04, 'pre_champs': 22.24, 'max': 23.54}